spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/jwt_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: roger3495
  jpa:
    hibernate:
      ddl-auto: create